import { LanguageProvider } from '@inlang/paraglide-next';
import "~/styles/globals.css";
import NextTopLoader from 'nextjs-toploader';
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = 'en';

  return (
    <LanguageProvider>
      <html lang={locale} className={`${GeistSans.variable}`}>
        <body>
          <NextTopLoader showSpinner={false} />
          <TRPCReactProvider>
            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </LanguageProvider>
  );
}
